version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NEXT_PUBLIC_BASE_URL=http://localhost:3005
      - NEXT_PUBLIC_BASE_URL_POSTS=https://jsonplaceholder.typicode.com